/*
 * Copyright (C) 2007 - 2014 Hyperweb2 All rights reserved.
 * GNU General Public License version 3; see www.hyperweb2.com/terms/
 */
package system.notification.view;

import javax.swing.JInternalFrame;
import system.common.MyJFrame;
import system.notification.controller.ControllerJFrameNotifiche;

/**
 *
 *
 */
public class JFrameNotifiche extends MyJFrame {
    /* Creates new form */

    public JFrameNotifiche(ControllerJFrameNotifiche controller, JInternalFrame iFrame) {
        super(controller, iFrame);
        initComponents();
        this.initialize();
    }

    public void initialize() {
        this.initialize(jButtonOut, jPanelContent, jTableNotifiche);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotifiche = new javax.swing.JTable();
        jPanelHeader = new javax.swing.JPanel();
        jPanelRicercaWEST = new javax.swing.JPanel();
        jCheckNonLette = new javax.swing.JCheckBox();
        jPanelFooter = new javax.swing.JPanel();
        jPanelEAST = new javax.swing.JPanel();
        jButtonOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelContent.setMinimumSize(new java.awt.Dimension(800, 601));
        jPanelContent.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(454, 405));

        jTableNotifiche.setAutoCreateRowSorter(true);
        jTableNotifiche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableNotifiche.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableNotifiche);

        jPanelContent.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelHeader.setLayout(new java.awt.BorderLayout());

        jPanelRicercaWEST.setMinimumSize(new java.awt.Dimension(200, 32));

        jCheckNonLette.setText("Solo non lette");
        jCheckNonLette.setToolTipText("");
        jCheckNonLette.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckNonLetteMouseClicked(evt);
            }
        });
        jPanelRicercaWEST.add(jCheckNonLette);

        jPanelHeader.add(jPanelRicercaWEST, java.awt.BorderLayout.WEST);

        jPanelContent.add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jPanelFooter.setLayout(new java.awt.BorderLayout());
        jPanelFooter.add(jPanelEAST, java.awt.BorderLayout.EAST);

        jButtonOut.setText("stacca");
        jButtonOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButtonOut, java.awt.BorderLayout.LINE_START);

        jPanelContent.add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutActionPerformed
        this.changeFrameState();
}//GEN-LAST:event_jButtonOutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        controller.doDefaultFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jCheckNonLetteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckNonLetteMouseClicked
        ((ControllerJFrameNotifiche) controller).refreshList(jCheckNonLette.isSelected());
    }//GEN-LAST:event_jCheckNonLetteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonOut;
    private javax.swing.JCheckBox jCheckNonLette;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelEAST;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelRicercaWEST;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNotifiche;
    // End of variables declaration//GEN-END:variables

}
