/*
 *  * Copyright (C) 2007 - 2014 Hyperweb2 All rights reserved
 *  * GNU General Public License version 3; see http://www.hyperweb2.com/terms/
 */

package system.report.view;

import javax.swing.JInternalFrame;
import system.common.MyJFrameController;
import system.common.MyJFrame;
import system.report.controller.ControllerJFrameSegnalazioniList;

public class JFrameSegnalazioniList extends MyJFrame {

    public JFrameSegnalazioniList(ControllerJFrameSegnalazioniList controller, JInternalFrame iFrame) {
        super(controller, iFrame);
        initComponents();
        initialize();
    }

    /**
     * Initialize the class.
     */
    private void initialize() {
        this.initialize(jButtonOut, rootPane, jTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        jPanelRicerca = new javax.swing.JPanel();
        jTextLoc = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanelSouth = new javax.swing.JPanel();
        jPanelBottomRight = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonApri = new javax.swing.JButton();
        jButtonOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chat list");
        setResizable(false);

        jPanelNorth.setLayout(new java.awt.BorderLayout());

        jTextLoc.setText("Luogo...");
        jTextLoc.setMinimumSize(new java.awt.Dimension(150, 31));
        jTextLoc.setPreferredSize(new java.awt.Dimension(150, 31));
        jPanelRicerca.add(jTextLoc);

        jButtonSearch.setText("Filtra");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanelRicerca.add(jButtonSearch);

        jPanelNorth.add(jPanelRicerca, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelContent.setLayout(new java.awt.BorderLayout());

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jScrollPane.setPreferredSize(new java.awt.Dimension(452, 300));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(jTable);

        jPanelCenter.add(jScrollPane, java.awt.BorderLayout.NORTH);

        jPanelContent.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setLayout(new java.awt.BorderLayout());

        jButtonCreate.setText("Crea");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        jPanelBottomRight.add(jButtonCreate);

        jButtonApri.setText("Apri Segnalazione Selezionata");
        jButtonApri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApriActionPerformed(evt);
            }
        });
        jPanelBottomRight.add(jButtonApri);

        jPanelSouth.add(jPanelBottomRight, java.awt.BorderLayout.EAST);

        jButtonOut.setText("Stacca");
        jButtonOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonOut, java.awt.BorderLayout.LINE_START);

        jPanelContent.add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApriActionPerformed
        ((MyJFrameController.HasChild)this.controller).openChild(jTable.getSelectedRow());
    }//GEN-LAST:event_jButtonApriActionPerformed

    private void jButtonOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutActionPerformed
        this.changeFrameState();
    }//GEN-LAST:event_jButtonOutActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        this.controller.refreshList(jTextLoc.getText());
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        ((ControllerJFrameSegnalazioniList)this.controller).openSendReport();
    }//GEN-LAST:event_jButtonCreateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApri;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonOut;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JPanel jPanelBottomRight;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelRicerca;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextLoc;
    // End of variables declaration//GEN-END:variables

}
