/*
 *  * Copyright (C) 2007 - 2014 Hyperweb2 All rights reserved
 *  * GNU General Public License version 3; see http://www.hyperweb2.com/terms/
 */
package system.test.view;

import javax.swing.JInternalFrame;
import system.common.MyJFrame;
import system.test.controller.ControllerJFrameTest;

public class JFrameTest extends MyJFrame {

    public JFrameTest(ControllerJFrameTest controller, JInternalFrame iFrame) {
        super(controller, iFrame);
        initComponents();
        initialize();
    }

    /**
     * Initialize the class.
     */
    private void initialize() {
        this.initialize(jButtonOut, rootPane, jTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonSegnalazioni = new javax.swing.JButton();
        jButtonTestUser = new javax.swing.JButton();
        jButtonInsertComment = new javax.swing.JButton();
        jButtonDelComment = new javax.swing.JButton();
        jPanelSouth = new javax.swing.JPanel();
        jPanelBottomRight = new javax.swing.JPanel();
        jButtonOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifica Distributore");
        setResizable(false);

        jPanelContent.setLayout(new java.awt.BorderLayout());

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jScrollPane.setPreferredSize(new java.awt.Dimension(452, 300));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setCellSelectionEnabled(true);
        jScrollPane.setViewportView(jTable);

        jPanelCenter.add(jScrollPane, java.awt.BorderLayout.NORTH);

        jButtonSegnalazioni.setText("Test Load Reports");
        jButtonSegnalazioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSegnalazioniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSegnalazioni);

        jButtonTestUser.setLabel("Test Load Users");
        jButtonTestUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTestUser);

        jButtonInsertComment.setText("Test Insert Comment");
        jButtonInsertComment.setToolTipText("");
        jButtonInsertComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertCommentActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsertComment);

        jButtonDelComment.setText("Test Del Comments");
        jButtonDelComment.setToolTipText("");
        jButtonDelComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelCommentActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelComment);

        jPanelCenter.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelContent.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setLayout(new java.awt.BorderLayout());
        jPanelSouth.add(jPanelBottomRight, java.awt.BorderLayout.EAST);

        jButtonOut.setText("Stacca");
        jButtonOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonOut, java.awt.BorderLayout.LINE_START);

        jPanelContent.add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertCommentActionPerformed
        ((ControllerJFrameTest)controller).insertCommento();
    }//GEN-LAST:event_jButtonInsertCommentActionPerformed

    private void jButtonDelCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelCommentActionPerformed
        ((ControllerJFrameTest)controller).deleteCommento();
    }//GEN-LAST:event_jButtonDelCommentActionPerformed

    private void jButtonTestUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestUserActionPerformed
        ((ControllerJFrameTest)controller).loadUtenti();
    }//GEN-LAST:event_jButtonTestUserActionPerformed

    private void jButtonOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutActionPerformed
        this.changeFrameState();
    }//GEN-LAST:event_jButtonOutActionPerformed

    private void jButtonSegnalazioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSegnalazioniActionPerformed
        ((ControllerJFrameTest)controller).loadSegnalazioni();
    }//GEN-LAST:event_jButtonSegnalazioniActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelComment;
    private javax.swing.JButton jButtonInsertComment;
    private javax.swing.JButton jButtonOut;
    private javax.swing.JButton jButtonSegnalazioni;
    private javax.swing.JButton jButtonTestUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBottomRight;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

}
