/*
 * Copyright (C) 2007 - 2014 Hyperweb2 All rights reserved.
 * GNU General Public License version 3; see www.hyperweb2.com/terms/
 */
package system.main.view;

import hwcore.modules.java.src.library.common.GuiTools;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import system.main.controller.ControllerJDialogLogin;
import system.main.controller.ControllerJFrameMain;
import system.user.controller.ControllerJFrameUser;

public class JDialogLogin extends javax.swing.JDialog {

    public ControllerJDialogLogin controller = null;

    public JDialogLogin(ControllerJDialogLogin controller) {
        super(ControllerJFrameMain.I().getMainFrame(), false);
        this.controller = controller;
        initComponents();
        initialize();
    }

    /**
     * Initialize the class.
     */
    private void initialize() {
        // ** inizializzazioni necessarie per visual editor eclipse **
        setContentPane(jPanelContent);
        setSize(new java.awt.Dimension(300, 350));
        GuiTools.setWindowCenterPosition(this);
        this.jTextFieldEmail.setText("test@test.it");
        this.jTextFieldPassword.setText("1");
        
        this.addWindowListener( new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent we) {
                        //System.exit(0);
                    }
        } );
        
        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Effettua il login");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanelContent.setLayout(null);

        jButtonLogin.setText("Entra");
        jButtonLogin.setToolTipText("");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelContent.add(jButtonLogin);
        jButtonLogin.setBounds(90, 210, 130, 33);
        jPanelContent.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(100, 90, 120, 31);
        jPanelContent.add(jTextFieldPassword);
        jTextFieldPassword.setBounds(100, 160, 120, 31);

        jLabel1.setText("Email:");
        jPanelContent.add(jLabel1);
        jLabel1.setBounds(100, 70, 60, 21);

        jLabel2.setText("Password:");
        jPanelContent.add(jLabel2);
        jLabel2.setBounds(100, 140, 120, 21);

        jButtonRegister.setText("Registrati");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanelContent.add(jButtonRegister);
        jButtonRegister.setBounds(90, 250, 130, 33);

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if (!this.controller.login(this.jTextFieldEmail.getText(), this.jTextFieldPassword.getText()))
            JOptionPane.showMessageDialog(this,"Email o password errata!", "WARNING",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.controller.close();
    }//GEN-LAST:event_formWindowClosed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            this.jButtonLoginActionPerformed(null);
        }
    }//GEN-LAST:event_formKeyPressed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        new ControllerJFrameUser(true);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPassword;
    // End of variables declaration//GEN-END:variables

}
