/*
 * Copyright (C) 2007 - 2014 Hyperweb2 All rights reserved.
 * GNU General Public License version 3; see www.hyperweb2.com/terms/
 */
package system.main.view;

import hwcore.modules.java.src.library.climenu.JTextConsole;
import java.awt.Dimension;
import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import system.chat.controller.ControllerJFrameChatList;
import system.common.MyJFrameController;
import system.main.controller.ControllerJDialogLogin;
import system.main.controller.ControllerJFrameMain;
import system.notification.controller.ControllerJFrameNotifications;
import system.news.controller.ControllerJFrameNewsList;
import system.emergencynumber.controller.ControllerJFrameNumbers;
import system.report.controller.ControllerJFrameReportsList;
import system.test.controller.ControllerJFrameTest;
import system.user.controller.ControllerJFrameUser;

/**
 *
 *
 */
public class JFrameMain extends javax.swing.JFrame {

    private static ControllerJFrameMain main;

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        main = ControllerJFrameMain.I();
        initComponents();
        initialize();
    }

    public JDesktopPane getjDesktopPane() {
        return jDesktopPane;
    }

    /**
     * Initialize the class.
     */
    private void initialize() {
        setContentPane(jPanelContent);
        setSize(new Dimension(800, 600));
        setPreferredSize(getSize());
        setExtendedState(MAXIMIZED_BOTH);

        PipedInputStream outPipe = new PipedInputStream();

        PrintStream outStream;
        try {
            outStream = new PrintStream(new PipedOutputStream(outPipe), true);
            System.setOut(outStream);
        } catch (IOException ex) {
            Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        JTextConsole.console(jTextAreaConsole, null, outPipe, null);
        new ControllerJDialogLogin();
    }

    private void frameClose(Class c) {
        main.getCtrl(c).dispose();
    }

    private void doFocus(Class c) {
        MyJFrameController ctrl = main.getCtrl(c);
        if (ctrl != null) {
            ctrl.doDefaultFocus();
        }
    }

    private <T extends MyJFrameController> void frameOpen(Class<T> ctrl) {
        if (main.getCtrl(ctrl) == null) {
            try {
                ControllerJFrameMain.I().setCtrl(ctrl.newInstance());
            } catch (InstantiationException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jInternalFrameChat = new javax.swing.JInternalFrame();
        jInternalFrameNotizie = new javax.swing.JInternalFrame();
        jInternalFrameNumeri = new javax.swing.JInternalFrame();
        jInternalFrameNotifiche = new javax.swing.JInternalFrame();
        jInternalFrameSegnalazioni = new javax.swing.JInternalFrame();
        jInternalFrameUtente = new javax.swing.JInternalFrame();
        jInternalFrameConsole = new javax.swing.JInternalFrame();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jInternalFrameTest = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuFinestre = new javax.swing.JMenu();
        jMenuItemUtente = new javax.swing.JMenuItem();
        jMenuItemNumeri = new javax.swing.JMenuItem();
        jMenuItemChat = new javax.swing.JMenuItem();
        jMenuItemNotifiche = new javax.swing.JMenuItem();
        jMenuItemNotizie = new javax.swing.JMenuItem();
        jMenuItemSegnalazioni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOuL Application");
        setMinimumSize(new java.awt.Dimension(640, 480));

        jPanelContent.setLayout(new java.awt.BorderLayout());

        jDesktopPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane.setAutoscrolls(true);
        jDesktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jInternalFrameChat.setClosable(true);
        jInternalFrameChat.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameChat.setIconifiable(true);
        jInternalFrameChat.setMaximizable(true);
        jInternalFrameChat.setResizable(true);
        jInternalFrameChat.setTitle("Chat");
        jInternalFrameChat.setName("chat"); // NOI18N
        jInternalFrameChat.setVisible(true);
        jInternalFrameChat.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameChatInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameChatInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameChatInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jDesktopPane.add(jInternalFrameChat);
        jInternalFrameChat.setBounds(0, 0, 640, 400);
        try {
            jInternalFrameChat.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrameNotizie.setClosable(true);
        jInternalFrameNotizie.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameNotizie.setIconifiable(true);
        jInternalFrameNotizie.setMaximizable(true);
        jInternalFrameNotizie.setResizable(true);
        jInternalFrameNotizie.setTitle("Notizie");
        jInternalFrameNotizie.setToolTipText("");
        jInternalFrameNotizie.setVisible(true);
        jInternalFrameNotizie.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNotizieInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNotizieInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNotizieInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jDesktopPane.add(jInternalFrameNotizie);
        jInternalFrameNotizie.setBounds(0, 0, 640, 400);
        try {
            jInternalFrameNotizie.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrameNumeri.setClosable(true);
        jInternalFrameNumeri.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameNumeri.setIconifiable(true);
        jInternalFrameNumeri.setMaximizable(true);
        jInternalFrameNumeri.setResizable(true);
        jInternalFrameNumeri.setTitle("Numeri di emergenza");
        jInternalFrameNumeri.setVisible(true);
        jInternalFrameNumeri.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNumeriInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNumeriInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNumeriInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jDesktopPane.add(jInternalFrameNumeri);
        jInternalFrameNumeri.setBounds(0, 0, 624, 371);
        try {
            jInternalFrameNumeri.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrameNotifiche.setClosable(true);
        jInternalFrameNotifiche.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameNotifiche.setIconifiable(true);
        jInternalFrameNotifiche.setMaximizable(true);
        jInternalFrameNotifiche.setResizable(true);
        jInternalFrameNotifiche.setTitle("Notifiche");
        jInternalFrameNotifiche.setToolTipText("");
        jInternalFrameNotifiche.setVisible(true);
        jInternalFrameNotifiche.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNotificheInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNotificheInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameNotificheInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jDesktopPane.add(jInternalFrameNotifiche);
        jInternalFrameNotifiche.setBounds(0, 0, 624, 371);

        jInternalFrameSegnalazioni.setClosable(true);
        jInternalFrameSegnalazioni.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameSegnalazioni.setIconifiable(true);
        jInternalFrameSegnalazioni.setMaximizable(true);
        jInternalFrameSegnalazioni.setResizable(true);
        jInternalFrameSegnalazioni.setTitle("Segnalazioni");
        jInternalFrameSegnalazioni.setVisible(true);
        jInternalFrameSegnalazioni.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameSegnalazioniInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameSegnalazioniInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameSegnalazioniInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jDesktopPane.add(jInternalFrameSegnalazioni);
        jInternalFrameSegnalazioni.setBounds(0, 0, 624, 371);
        try {
            jInternalFrameSegnalazioni.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrameUtente.setClosable(true);
        jInternalFrameUtente.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameUtente.setIconifiable(true);
        jInternalFrameUtente.setMaximizable(true);
        jInternalFrameUtente.setResizable(true);
        jInternalFrameUtente.setTitle("Utente");
        jInternalFrameUtente.setName("chat"); // NOI18N
        jInternalFrameUtente.setVisible(true);
        jInternalFrameUtente.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameUtenteInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameUtenteInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameUtenteInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jDesktopPane.add(jInternalFrameUtente);
        jInternalFrameUtente.setBounds(0, 0, 640, 400);
        try {
            jInternalFrameUtente.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrameConsole.setClosable(true);
        jInternalFrameConsole.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameConsole.setIconifiable(true);
        jInternalFrameConsole.setMaximizable(true);
        jInternalFrameConsole.setResizable(true);
        jInternalFrameConsole.setTitle("Console");
        jInternalFrameConsole.setName("console"); // NOI18N
        jInternalFrameConsole.setVisible(true);
        jInternalFrameConsole.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameConsoleInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameConsoleInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameConsoleInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPane.setViewportView(jTextAreaConsole);

        jInternalFrameConsole.getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        jDesktopPane.add(jInternalFrameConsole);
        jInternalFrameConsole.setBounds(0, 0, 640, 400);
        try {
            jInternalFrameConsole.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrameTest.setClosable(true);
        jInternalFrameTest.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameTest.setIconifiable(true);
        jInternalFrameTest.setMaximizable(true);
        jInternalFrameTest.setResizable(true);
        jInternalFrameTest.setTitle("Test");
        jInternalFrameTest.setName("test"); // NOI18N
        jInternalFrameTest.setVisible(true);
        jInternalFrameTest.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameTestInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameTestInternalFrameDeiconified(evt);
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrameTestInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jDesktopPane.add(jInternalFrameTest);
        jInternalFrameTest.setBounds(0, 0, 640, 400);
        try {
            jInternalFrameTest.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelContent.add(jDesktopPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuFinestre.setText("Finestre");

        jMenuItemUtente.setText("Utente");
        jMenuItemUtente.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jMenuItemUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUtenteActionPerformed(evt);
            }
        });
        jMenuFinestre.add(jMenuItemUtente);

        jMenuItemNumeri.setText("Numeri Emergenza");
        jMenuItemNumeri.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jMenuItemNumeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNumeriActionPerformed(evt);
            }
        });
        jMenuFinestre.add(jMenuItemNumeri);

        jMenuItemChat.setText("Chat");
        jMenuItemChat.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jMenuItemChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChatActionPerformed1(evt);
            }
        });
        jMenuFinestre.add(jMenuItemChat);

        jMenuItemNotifiche.setText("Notifiche");
        jMenuItemNotifiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotificheActionPerformed(evt);
            }
        });
        jMenuFinestre.add(jMenuItemNotifiche);

        jMenuItemNotizie.setText("Notizie");
        jMenuItemNotizie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotizieActionPerformed(evt);
            }
        });
        jMenuFinestre.add(jMenuItemNotizie);

        jMenuItemSegnalazioni.setText("Segnalazioni");
        jMenuItemSegnalazioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSegnalazioniActionPerformed(evt);
            }
        });
        jMenuFinestre.add(jMenuItemSegnalazioni);

        jMenuBar1.add(jMenuFinestre);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(775, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNumeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNumeriActionPerformed
        frameOpen(ControllerJFrameNumbers.class);
}//GEN-LAST:event_jMenuItemNumeriActionPerformed

    private void jMenuItemUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUtenteActionPerformed
        frameOpen(ControllerJFrameUser.class);
}//GEN-LAST:event_jMenuItemUtenteActionPerformed

    private void jMenuItemChatActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChatActionPerformed1
        frameOpen(ControllerJFrameChatList.class);
    }//GEN-LAST:event_jMenuItemChatActionPerformed1

    private void jInternalFrameNumeriInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNumeriInternalFrameClosing
        frameClose(ControllerJFrameNumbers.class);
    }//GEN-LAST:event_jInternalFrameNumeriInternalFrameClosing

    private void jInternalFrameNumeriInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNumeriInternalFrameDeiconified
        jMenuItemNumeri.doClick();
    }//GEN-LAST:event_jInternalFrameNumeriInternalFrameDeiconified

    private void jInternalFrameNotizieInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNotizieInternalFrameClosing
        frameClose(ControllerJFrameNewsList.class);
    }//GEN-LAST:event_jInternalFrameNotizieInternalFrameClosing

    private void jInternalFrameNotizieInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNotizieInternalFrameDeiconified
        jMenuItemNotizie.doClick();
    }//GEN-LAST:event_jInternalFrameNotizieInternalFrameDeiconified

    private void jInternalFrameNotificheInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNotificheInternalFrameClosing
        frameClose(ControllerJFrameNotifications.class);
    }//GEN-LAST:event_jInternalFrameNotificheInternalFrameClosing

    private void jInternalFrameNotificheInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNotificheInternalFrameDeiconified
        jMenuItemNotifiche.doClick();
    }//GEN-LAST:event_jInternalFrameNotificheInternalFrameDeiconified

    private void jMenuItemNotificheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotificheActionPerformed
        frameOpen(ControllerJFrameNotifications.class);
    }//GEN-LAST:event_jMenuItemNotificheActionPerformed

    private void jInternalFrameChatInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameChatInternalFrameDeiconified
        jMenuItemChat.doClick();
    }//GEN-LAST:event_jInternalFrameChatInternalFrameDeiconified

    private void jInternalFrameChatInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameChatInternalFrameClosing
        frameClose(ControllerJFrameChatList.class);
    }//GEN-LAST:event_jInternalFrameChatInternalFrameClosing

    private void jInternalFrameSegnalazioniInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameSegnalazioniInternalFrameClosing
        frameClose(ControllerJFrameReportsList.class);
    }//GEN-LAST:event_jInternalFrameSegnalazioniInternalFrameClosing

    private void jInternalFrameSegnalazioniInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameSegnalazioniInternalFrameDeiconified
        jMenuItemSegnalazioni.doClick();
    }//GEN-LAST:event_jInternalFrameSegnalazioniInternalFrameDeiconified

    private void jMenuItemNotizieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotizieActionPerformed
        frameOpen(ControllerJFrameNewsList.class);
    }//GEN-LAST:event_jMenuItemNotizieActionPerformed

    private void jInternalFrameNotizieInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNotizieInternalFrameActivated
        doFocus(ControllerJFrameNewsList.class);
    }//GEN-LAST:event_jInternalFrameNotizieInternalFrameActivated

    private void jInternalFrameChatInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameChatInternalFrameActivated
        doFocus(ControllerJFrameChatList.class);
    }//GEN-LAST:event_jInternalFrameChatInternalFrameActivated

    private void jInternalFrameNotificheInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNotificheInternalFrameActivated
        doFocus(ControllerJFrameNotifications.class);
    }//GEN-LAST:event_jInternalFrameNotificheInternalFrameActivated

    private void jInternalFrameSegnalazioniInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameSegnalazioniInternalFrameActivated
        doFocus(ControllerJFrameReportsList.class);
    }//GEN-LAST:event_jInternalFrameSegnalazioniInternalFrameActivated

    private void jInternalFrameNumeriInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameNumeriInternalFrameActivated
        doFocus(ControllerJFrameNumbers.class);
    }//GEN-LAST:event_jInternalFrameNumeriInternalFrameActivated

    private void jInternalFrameUtenteInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameUtenteInternalFrameClosing
        frameClose(ControllerJFrameUser.class);
    }//GEN-LAST:event_jInternalFrameUtenteInternalFrameClosing

    private void jInternalFrameUtenteInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameUtenteInternalFrameDeiconified
        jMenuItemUtente.doClick();
    }//GEN-LAST:event_jInternalFrameUtenteInternalFrameDeiconified

    private void jInternalFrameUtenteInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameUtenteInternalFrameActivated
        doFocus(ControllerJFrameNotifications.class);
    }//GEN-LAST:event_jInternalFrameUtenteInternalFrameActivated

    private void jMenuItemSegnalazioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSegnalazioniActionPerformed
        frameOpen(ControllerJFrameReportsList.class);
    }//GEN-LAST:event_jMenuItemSegnalazioniActionPerformed

    private void jInternalFrameConsoleInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameConsoleInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameConsoleInternalFrameClosing

    private void jInternalFrameConsoleInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameConsoleInternalFrameDeiconified
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameConsoleInternalFrameDeiconified

    private void jInternalFrameConsoleInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameConsoleInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameConsoleInternalFrameActivated

    private void jInternalFrameTestInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameTestInternalFrameClosing
        frameClose(ControllerJFrameTest.class);
    }//GEN-LAST:event_jInternalFrameTestInternalFrameClosing

    private void jInternalFrameTestInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameTestInternalFrameDeiconified
        //MainClass.I().setCtrl(new ControllerJFrameTest());
    }//GEN-LAST:event_jInternalFrameTestInternalFrameDeiconified

    private void jInternalFrameTestInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrameTestInternalFrameActivated
        ControllerJFrameMain.I().setCtrl(new ControllerJFrameTest());
    }//GEN-LAST:event_jInternalFrameTestInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    public javax.swing.JInternalFrame jInternalFrameChat;
    public javax.swing.JInternalFrame jInternalFrameConsole;
    public javax.swing.JInternalFrame jInternalFrameNotifiche;
    public javax.swing.JInternalFrame jInternalFrameNotizie;
    public javax.swing.JInternalFrame jInternalFrameNumeri;
    public javax.swing.JInternalFrame jInternalFrameSegnalazioni;
    public javax.swing.JInternalFrame jInternalFrameTest;
    public javax.swing.JInternalFrame jInternalFrameUtente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFinestre;
    private javax.swing.JMenuItem jMenuItemChat;
    private javax.swing.JMenuItem jMenuItemNotifiche;
    private javax.swing.JMenuItem jMenuItemNotizie;
    private javax.swing.JMenuItem jMenuItemNumeri;
    private javax.swing.JMenuItem jMenuItemSegnalazioni;
    private javax.swing.JMenuItem jMenuItemUtente;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextAreaConsole;
    // End of variables declaration//GEN-END:variables
}
